#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use App\Commands\SayHelloCommand;
use App\Commands\SeedUser;

$dotenv = new Dotenv\Dotenv(__DIR__ . '/');
$dotenv->load();

$application = new Application();

$application->add(new seedUser());

$application->run();
